### ISSUE TITLE
Modifying Hawkeye's limits

### ISSUE THREAD

**Issue by dspringer** [Stono/hawkeye#14] opened 2017-09-26 20:03 UTC
Just tried to scan a large project, and hawkeye was not a fan on many levels.
Output:
```
[info] Welcome to Hawkeye v0.14.12!

[info] File Contents dynamically loaded
[info] Entropy dynamically loaded
[info] Example Module dynamically loaded
[info] Secret Files dynamically loaded
[info] Node Constant Hashtable Seed check dynamically loaded
[info] Node CrossEnv malware check dynamically loaded
[info] Node Check Updates dynamically loaded
[info] Node Security Project dynamically loaded
[info] Bundler Scan dynamically loaded
[info] Exclusion patterns: ^node_modules/, ^.git/, ^.git-crypt/, package-lock.json
[info] git repo detected, will only use git tracked files
[info]  -> git ls-tree --full-tree --name-only -r HEAD
[info] Files excluded by exclusion patterns: 0
[warn] Hawkeye limits the number of files to scan to 1000, and you have 1092
[warn] Please tweak your .hawkeyeexclude
[info] Files included in scan: 1000
[info] Target for scan: /target
[info] Running module File Contents
[warn] File which exceeds 80kb limited detected: /target/packages/server-web/public/test/test.complete.js
[warn] File which exceeds 80kb limited detected: /target/packages/web/src/components/tester/TimeTester.jsx
/hawkeye/lib/modules/content/index.js:19
    return item => {
           ^

RangeError: Maximum call stack size exceeded
    at Object.item [as contentMatcher] (/hawkeye/lib/modules/content/index.js:19:12)
    at Object.pattern.check (/hawkeye/lib/modules/content/index.js:45:34)
    at fileManager.readFile (/hawkeye/lib/modules/content/index.js:67:21)
    at Object.FileManager.self.readFile (/hawkeye/lib/fileManager.js:170:12)
    at async.eachSeries (/hawkeye/lib/modules/content/index.js:65:23)
    at /hawkeye/node_modules/async/dist/async.js:3083:16
    at replenish (/hawkeye/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/hawkeye/node_modules/async/dist/async.js:931:17)
    at /hawkeye/node_modules/async/dist/async.js:906:16
    at fileManager.readFile (/hawkeye/lib/modules/content/index.js:68:13)

```

Questions:
- Where can I find the .hawkeyeexclude to tweak?  Will changing this file allow me to scan more than 1000 files? Or is there another way for me to increase the number of files I can scan? I searched the repo for .hawkeyeexclude and it seems it only shows up in that print statement.
- Is there a reason for the 80kb limit? Can I change it?
- How can I fix that breaking error?

Thanks for all your help!

**Comment by Stono** [comment] 2017-09-27 10:32
Is this project private?
Could you send me a tarball?

**Comment by dspringer** [comment] 2017-09-27 15:13
It is private and my employer wouldn't be okay with me posting it. Sorry :(

**Comment by Stono** [comment] 2017-10-24 11:26
@dspringer apologies for the epic delay, I've been travelling a lot recently.
I believe https://github.com/Stono/hawkeye/pull/18 will fix this issue, I'll merge it later today once people have cast their eyes over it.

**Comment by Stono** [comment] 2017-10-24 11:27
Closing this issue as it's a duplicate of https://github.com/Stono/hawkeye/issues/16

**Closed by Stono** 2017-10-24 11:27 UTC
Labels: bug
